name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - '.github/workflows/**'

env:
  IMAGE_NAME: "simaofsilva/renovatebot-docker-buildpack"
  REPO_URL: "https://github.com/renovatebot/docker-buildpack"
  LOCAL_PATH: "/tmp/docker-buildpack"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone original repository
        run: |
          git clone ${{ env.REPO_URL }} ${{ env.LOCAL_PATH }}

      - name: Check if custom Dockerfile is been used
        run: |
          cp Dockerfile ${{ env.LOCAL_PATH }}
          cat ${{ env.LOCAL_PATH }}/Dockerfile

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.LOCAL_PATH }}
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:6
            ${{ env.IMAGE_NAME }}:latest
